### ISSUE TITLE
Add azure.json to .gitignore at Angular project

### ISSUE THREAD

**Issue by softchris** [Azure/ng-deploy-azure#11]
1. add disclaimer to README that you have to do this yourself
2. solve it with Schematics and `azure.json` entry to `.gitignore`

**Comment by shmool** [comment]
How does it work for firebase? I don’t think it’s added to .gitignore, or even mentioned on readme or anywhere else.
The data on azure.json is not very problematic. It’s not the credentials.
We already clearly note that this file is created. We don’t do “git add” on it.
And not everybody uses git… I guess there are other source control tools that are used.

**Comment by shmool** [comment]
azure.json remains part of the Angular project, and will be shared by git.
https://github.com/Azure/ng-deploy-azure/pull/42 uses the existing configuration and allows to reconfigure.
