### ISSUE TITLE
Deploy command should either build or not build consistently

### ISSUE THREAD

**Issue by johnpapa** [Azure/ng-deploy-azure#23]
**Describe the bug**

**To Reproduce**

```
ng new hello-world --defaults
cd hello-world
ng add @azure/ng-deploy
ng run hello-world:deploy
```

The app builds and then deploys.

Now  change something in the app. Then run ...

```
ng run hello-world:deploy
```

Browser to the site in Azure. Notice that what is deployed does not contain your changes. It appears that the deploy command is not building if something already exists in the `dist/` folder.

**Expected behavior**
I expected that the deploy command would have always re-built the angular app first or never rebuild it.  Options:

1. always rebuild before deploying `ng build --prod`
2. never rebuild before deploying. but this would cause an error or the results i mention above.
3. prompt the user to rebuild

I like 1 or 3.

Thoughts?

**Comment by JohannesHoppe** [comment]
I have started a discussion here:
https://github.com/angular-schule/ngx-deploy-starter/issues/1

It would be great if we could find a common approach so that the expected behaviour and usability of the different builders are consistent.

**Comment by JohannesHoppe** [comment]
There were a few proposals on [this topic](angular-schule/ngx-deploy-starter#1). Currently, there could be a majority for the following options:
- `--configuration` (alias `-c`): A named build target, as specified in the "configurations" section of angular.json
- `--no-build`: Skip build process during deployment
