### ISSUE TITLE
DOC: Move local dev and testing instructions to Contributing.md

### ISSUE THREAD

**Issue by softchris** [Azure/ng-deploy-azure#35]
## Description

add to contribution file
- npm pack
- npm install [zip file]

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Closing issues

Put closes #XXXX in your comment to auto-close the issue that your PR fixes (if such).

## Assignee

Please add yourself as the assignee

## Projects

Please add relevant projects so this issue can be properly tracked.

**Comment by santoshyadav198613** [comment]
Hi @softchris  I will take care of it. Will raise the PR in a few hours.

**Comment by santoshyadav198613** [comment]
https://github.com/Azure/ng-deploy-azure/pull/38
