### ISSUE TITLE
Process to publish pull requests for feature preview

### ISSUE THREAD

**Issue by elvirdolic** [Azure/ng-deploy-azure#51]
## Description

We would like to publish a feature/preview site to azure storage for each pull request. The process would be

- Deploy angular to azure blob storage
- Create comment in Azure Devops / GitHub with preview url
- Update deployment on new pushes
- Delete storage account when PR get's merged

- Maybe this can be a build task for azure devops / github actions?

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Projects

I would like to contribute here but I would need some support :)

**Comment by manekinekko** [comment]
> Maybe this can be a build task for azure devops / github actions?

Related issue: https://github.com/Azure/ng-deploy-azure/issues/52

**Comment by manekinekko** [comment]
Hi @elvirdolic would you mind trying out the new CI feature and let's know? Please also open a new issue if needed. I'm going to close this one.

CI docs: https://github.com/Azure/ng-deploy-azure#continuous-integration-mode-
