### ISSUE TITLE
Cant install package

### ISSUE THREAD

**Issue by slubowsky** [Azure/ng-deploy-azure#53]
**Describe the bug**
Attempted to install by running
`ng add @azure/ng-deploy`
Install failed.
First saw error messages that needed python 2.7. Installed that.
Then saw error messages that needed windows SDK 8.1. Installed that.
Now getting error message:
`TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\my-app\node_modules\get-cursor-position\build\pos.vcxproj`]
I give up :(

**To Reproduce**
ng add @azure/ng-deploy

**Expected behavior**
package should be added

**Desktop:**
 - OS: Windows 10

**Additional context**
Angular cli 8.3.1

**Comment by shmool** [comment]
Thanks, @slubowsky! Looking into this.
IMO these packages should be optional. They probably belong to development env.

**Comment by sinedied** [comment]
@shmool this issue is already fixed on master, just need a new release :wink:
