### ISSUE TITLE
ng deploy fails when using an existing resource group and storage account during ng add

### ISSUE THREAD

**Issue by sinedied** [Azure/ng-deploy-azure#79]
**Describe the bug**
When invoking `ng add` using an existing resource group and storage account, `ng deploy` will fail with the following error:
```
Error when trying to deploy: 
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:0a02c7fb-101e-0133-3bf5-7229ae000000
Time:2019-09-24T16:33:50.0066513Z</Message></Error>
```

**To Reproduce**
1. `ng add @azure/ng-deploy --resourceGroup existing-rg--account existingstorage`
2. `ng deploy`

**Comment by Githamza** [comment]
You should go on azure portal , to you storage storage account and enable static websites
![image](https://user-images.githubusercontent.com/11578288/66518940-984be880-eae6-11e9-9d71-14b52d23052b.png)

**Comment by manekinekko** [comment]
@sinedied did @Githamza solution fixed your issue? Please reopen this issue if you still need help.
