### ISSUE TITLE
Fix @types/ascii-progress typings issue

### ISSUE THREAD

**Issue by johnpapa** [Azure/ng-deploy-azure#9]
We currently set `noImplicitAny` to `false`. This may not be ideal. Another option is to fix the typings below locally. Or to fix them in the library's github repo with a PR.

Putting this here so we do not forget

```
> ng-deploy-azure@0.1.0-beta.1 build /Users/papa/_git/ng-deploy-azure
> tsc -p tsconfig.json

src/builders/actions/deploy.ts:19:30 - error TS7016: Could not find a declaration file for module 'ascii-progress'. '/Users/papa/_git/ng-deploy-azure/node_modules/ascii-progress/index.js' implicitly has an 'any' type.
  Try `npm install @types/ascii-progress` if it exists or add a new declaration (.d.ts) file containing `declare module 'ascii-progress';`
```

**Comment by softchris** [comment]
Fixed by https://github.com/Azure/ng-deploy-azure/pull/8

**Comment by johnpapa** [comment]
#8 sets it to false, IIRC. What I am suggesting here is that we fix the typings issue for a longer term solution. Unless we want implicit any to be disabled for the entire project?

**Comment by johnpapa** [comment]
we may be able to fix this by ...

>  add a new declaration (.d.ts) file containing `declare module 'ascii-progress';`

then we dont turn it off for the entire project

**Comment by softchris** [comment]
Shmuela fixed this with just what you suggested, i.e declaration file. Closing this issue
